### ISSUE TITLE
Orchil doesn't set background colour, link colour, etc. from SkotOS server-side colour theme

### ISSUE THREAD

**Issue by noahgibbs** [ChatTheatre/orchil#19]
As @AnthonyHJ says:

~~~
The background colour is sent in a <body> tag when the theme is loaded.

For example, <body bgcolor='#404040' text='#F0F0F0' link='#5ABBA1' plink='#5ABBA1'> is returned for the retro theme in Castle Marrach.
~~~

There's actually code in Orchil that recognises that the body tag is special and a commented-out line that looks like it was supposed to use it. It just currently does nothing.

CC @kurzon-marrach

**Comment by noahgibbs** [comment]
Huh. At this point, cold-boot SkotOS (https://github.com/ChatTheatre/SkotOS) does *not* send a body tag in its default theme and configuration. I'll play with themes a bit, see if I can get it to do so. I see old code that looks like ~TextIF/obj/user.c used to always send one, but now it doesn't.

**Comment by noahgibbs** [comment]
Ah! Part of the problem is that the theme_initialize method was commented out in cold-boot SkotOS (commit cb4d97fe4891a1e698a83a25ae767860ad6c254c) because it "violated HTML5" - I'm guessing something wasn't liking the unterminated open body tag?

So that's why I'm seeing no body tag and only commented-out code trying to send it.

**Comment by noahgibbs** [comment]
Okay, added the ability in Orchil to set the theme to "skotos", which will wait and assume the server will set the theme (if that doesn't happen, it's quite plain.) Currently "skotos" theme only respects text colour and background colour, but it basically seems to work well with Eruption, for instance. Would love to talk to @AnthonyHJ and/or @kurzon-marrach about whether this is what they're looking for and/or what should change.

PR 22, linked above, is the code change for this.

![Screenshot 2021-02-26 at 14 02 28](https://user-images.githubusercontent.com/82408/109310791-e6c56880-783c-11eb-8110-8b72fa73199c.png)

**Comment by kurzon-marrach** [comment]
I might need a moment of clarification before I can answer.

Up to this point, the client side themes set via _clientpref_ haven't, as far as I understand it, had any real change other than changing the background colour. None of the four different built in themes (light/dark/dark_hc/terminal) have ever actually changed the text colours at least in the Marrach theatre; the only function served by changing between those themes has been to change the background colour (and the latter 3 themes all seem to have the same bg colour).

With the addition of the background_color _clientpref_ setting added yesterday, it would therefore seem to me that no further purpose exists for switching between the four client side themes, as the only function that served is now met by this new setting.

My understanding then, is that you've added a 5th orchil side theme called "skotos", which respects the server side background colour without needing to set a client side background_color via _clientpref_? If that's the case, then that would address any lingering concerns with regard's to Orchil's theme colors and related issues. And if so I might argue that at that point we should just set the default theme to "skotos" and remove the other 4 client side themes as redundant, along with the background_color _clientpref_ setting.

Let me know if I'm misunderstanding.

**Comment by AnthonyHJ** [comment]
I can only speak for my own implementation, but Castle Marrach uses links for some functionality and so I personally have Merciful apply the 'link' colour as a style to all the A tags in the main output window.

**Comment by noahgibbs** [comment]
You're correct that I have added a fifth client-side theme called "skotos" which respects the server-side theme. If you *also* set a background_color preference then the background_color set via clientpref would override everything else. But it may no longer be useful. Certainly you would no longer need it to get the server background colour - that is set automatically to whatever your server-side theme specifies.

I'm considering setting the default theme to skotos but wanted to talk to you first. The other themes might still be potentially useful for non-SkotOS servers. But they're a lot less useful once the "skotos" theme is in place, I agree. The only reason I won't remove them immediately is because the current version of cold-boot ChatTheatre/SkotOS actually doesn't send the body tag - I'll be fixing that very soon too.

**Comment by noahgibbs** [comment]
@AnthonyHJ cool - I can add that easily enough. I assume vlink is "visited link". Any idea what plink is?

**Comment by noahgibbs** [comment]
Also, @kurzon-marrach, I think that the themes changed the *unmodified* text colour with no tags. But yeah, they don't change the tagged text.

**Comment by AnthonyHJ** [comment]
We're looking at 20-year old web-development patterns, so pre HTML5 here.

link is the normal A colour ('a' in CSS)
alink is the colour of the link while you are clicking it ('a:active' in CSS)
vlink is the link if you have visited it ('a:visited' in CSS)
plink may be a custom value, I can't even find a reference to it

**Comment by noahgibbs** [comment]
Hm. I can find things that *set* plink, but only to (always) the same value as "link". So I can probably ignore it.

**Comment by kurzon-marrach** [comment]
> I'm considering setting the default theme to skotos but wanted to talk to you first. The other themes might still be potentially useful for non-SkotOS servers. But they're a lot less useful once the "skotos" theme is in place, I agree. The only reason I won't remove them immediately is because the current version of cold-boot ChatTheatre/SkotOS actually doesn't send the body tag - I'll be fixing that very soon too.

My experience thus far has been that the other themes don't actually change anything but the background color. Perhaps it's the case that they do for non-SkotOS theatres? When originally poking around the colouring issues, I tried disabling all my server side themes `@profile theme none` and still could only manage black text with white background on the the light theme, and white text on black background with the three remaining themes. 

Here's an example of "dark" with no server side theme set:

![theme_default_clienttheme_dark](https://user-images.githubusercontent.com/72933803/109357523-b7bcf000-7858-11eb-9903-5495224d50d1.png)

The last I heard from Orchil's original writer also seemed to imply he couldn't get the client side themes working because they were "incompatible with how SkotOS built styling support" -- but if they still have use for non-SkotOS theatres then absolutely keep them. If I really desire I can just patch them out for CM exclusively - there's little profit in keeping customization options that are defunct at best and could cause user error generated confusion at worst (ie: someone goofs around with `clientpref background_color` not realizing it will override other things and doesn't understand why suddenly every theme has a bright blue background).

It _does_ beg the question of what happens to those individuals who have already saved their clientpref settings to one of the existing themes before I remove them? Perhaps just a one-time error on login at which point it would switch them to the default "skotos", but perhaps not.

> Also, @kurzon-marrach, I think that the themes changed the _unmodified_ text colour with no tags. But yeah, they don't change the tagged text.

FYI as far as I know, all text falls under some atag or another, we have an `<atag tag="default">` which covers all text that doesn't fall under the other existing tags.

Semi-related but might be useful for you; I'm not sure if +kpe functions in Gables or if it's a Marrach specific tool, but it has a Theme Editor function built in that lets you browse and update existing server side themes. It lists, as far as I know, all existing tags supported by the server, including a handful that I've never seen used and typically remain blank on the existing themes.

![theme_editor_kpe](https://user-images.githubusercontent.com/72933803/109358467-2a7a9b00-785a-11eb-98b0-13843af23113.png)

**Comment by AnthonyHJ** [comment]
I have themes 100% supported in Merciful by inserting a &lt;style> tag at the end of the &lt;header> with basic  CSS. I have a bit more going on, but the only three you need to set are:
- main output { background-color } (background variable -> shows up as 'bgcolor' in the body tag)
- main output { color } (text variable -> shows up as 'text' in the body tag)
- main output links { color } (link variable -> shows up as 'link' in the body tag)

All other colours are set explicitly by the HTML font tags.

**Comment by noahgibbs** [comment]
Hm. It looks like the light and dark themes *do* affect the preset colours like "green", "black", etc, via the "genblack", "gengreen", etc CSS classes. For instance "genblack" is #060b0e for the light theme, but #FFFFFF (white) for the dark theme. There's also a bit of table theming, though I'm not sure what all uses tables other than the clientprefs. In any case, I think the overriding of the generic colours is a bad idea and I may remove it in a later PR.

I'm making server-side theming the default in this PR. It'll fix some problems we've been seeing. Once the corresponding server-side PR is merged, it'll all work out nicely.

I've just added support for link, alink and vlink server-side styling. I'm going to ignore plink until I see a reasonable use of it in the wild (and probably until/unless somebody complains.)
